### ISSUE TITLE
Deprecation Issues

### ISSUE THREAD

**Issue by beckobert** [mccullaghlab/GMM-Positions#1]
Hello,

I don't know if this repository is still maintained, but I have found issues with deprecations in dependencies.

The first one is that `sklearn` is now `scikit-learn`, which required a change in `pyproject.toml`.
The second one is that the type `np.int` is used in multiple files, while numpy deprecated it and insists on using simple `int` as a dtype.

These were all errors I have found. I could open a pull request to fix these problems, but this might be more complicated than necessary.

**Comment by mccullaghlab** [comment]
Thanks for letting me know.  I will try and fix them.   I do not maintain this repo much anymore as I have written a pyTorch version that is much faster (https://github.com/mccullaghlab/shapeGMMTorch).  I will also add a statement to this effect in the README for this repo.  Thanks again.

**Comment by mccullaghlab** [comment]
I updated the repo on github to fix these issues

**Comment by beckobert** [comment]
Thank you.
I was also not aware that there is a PyTorch version, I will check it out.
